steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.prod', '-t', 'us-central1-docker.pkg.dev/baraiyq-app-438307/baraiyq-backend/baraiyq-backend:0.0.4', '--no-cache', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/baraiyq-app-438307/baraiyq-backend/baraiyq-backend:0.0.4']

options:
  logging: CLOUD_LOGGING_ONLY