version: '3.8'

services:
  backend:
    image: demisto/fastapi:0.115.0.113380
    container_name: fastapi_app
    restart: always
    build:
      context: ./baraiyq-app-backend
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - ./baraiyq-app-backend:/app
    env_file:
      - ./.env
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
