apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: baraiyq-backend-service
spec: 
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/baraiyq-app-438307/baraiyq-backend/baraiyq-backend:latest
          env:
          ports:
            - containerPort: 8080