POSTGRES_USER = "axxermekya.ru"
POSTGRES_PASSWORD = "postgres123"
POSTGRES_DB = "baraiyq"
POSTGRES_HOST = "localhost"


DATABASE_URL = f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}/{POSTGRES_DB}"

