name: Deploy to Google Compute Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}
          logout: false
          

      - name: Build and Push Docker Image
        run: |
          docker build -t helfemida/baraiyq-app-backend:latest .
          docker push helfemida/baraiyq-app-backend:latest

      - name: SSH into VM and run Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USER }}
          key: ${{ secrets.GCE_KEY }}
          script: |
            docker pull helfemida/baraiyq-app-backend:latest
            docker run -d -p 80:8000 helfemida/baraiyq-app-backend:latest
